export const ITEM_API_FAIL = "ITEM_API_FAIL";

// Mint Acitvity
export const POST_MINT_ACTIVITY = "POST_MINT_ACTIVITY";
export const POST_MINT_ACTIVITY_FAIL = "POST_MINT_ACTIVITY_FAIL";
export const POST_MINT_ACTIVITY_SUCCESS = "POST_MINT_ACTIVITY_SUCCESS";

// Item List
export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";

export const NFTS_RRC_TO_MAINBUCKET_REQUEST = "NFTS_RRC_TO_MAINBUCKET_REQUEST";
export const NFTS_RRC_TO_MAINBUCKET_SUCCESS = "NFTS_RRC_TO_MAINBUCKET_SUCCESS";
export const NFTS_RRC_TO_MAINBUCKET_FAIL = "NFTS_RRC_TO_MAINBUCKET_FAIL";

export const GET_USER_MINTED_NFTS_COUNT_REQUEST = "GET_USER_MINTED_NFTS_COUNT_REQUEST";
export const GET_USER_MINTED_NFTS_COUNT_SUCCESS = "GET_USER_MINTED_NFTS_COUNT_SUCCESS";
export const GET_USER_MINTED_NFTS_COUNT_FAIL = "GET_USER_MINTED_NFTS_COUNT_FAIL";