export const REGISTER_USER_WITH_EMAIL = "REGISTER_USER_WITH_EMAIL";
export const REGISTER_USER_WITH_EMAIL_FAIL= "REGISTER_USER_WITH_EMAIL_FAIL";
export const REGISTER_USER_WITH_EMAIL_SUCCESS = "REGISTER_USER_WITH_EMAIL_FAIL_SUCCESS";

