export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const LINK_WALLET = "LINK_WALLET";
export const LINK_WALLET_FAIL = "LINK_WALLET_FAIL";
export const LINK_WALLET_SUCCESS = "LINK_WALLET_SUCCESS";

export const UNLINK_WALLET = "UNLINK_WALLET";
export const UNLINK_WALLET_FAIL = "UNLINK_WALLET_FAIL";
export const UNLINK_WALLET_SUCCESS = "UNLINK_WALLET_SUCCESS";

export const CHECK_CONNECT_WALLET = "CHECK_CONNECT_WALLET";
export const CHECK_CONNECT_WALLET_FAIL = "CHECK_CONNECT_WALLET_FAIL";
export const CHECK_CONNECT_WALLET_SUCCESS = "CHECK_CONNECT_WALLET_SUCCESS";